= Donjon Quick Reference Guide
Adam Parcher
:toc: preamble

Based upon the tabletop RPG Donjon[https://github.com/adamparcher/donjon-reference/blob/main/Donjon_Rules.adoc] by Clinton R. Nixon.

Donjon Quick Reference Guide © 2025 by Adam Parcher is licensed under https://creativecommons.org/licenses/by-sa/4.0/[CC BY-SA 4.0]

== Attributes
[cols="1,1,1"]
|===
|Attribute|Abbreviation|Description

|Virility
|Vir
|physical actions, determining the weight of armor and weapons you can carry, and inflicting damage.

|Cerebrality
|Cer
|contests of wit, for spell-casting, provisions tests.

|Discernment
|Dis
|aka "common sense"; used to perceive hidden or unclear things, resist the influence of others, and ignore mind-affecting magic.

|Adroitness
|Adr
|used in actions requiring finesse and skill, attacking with a weapon, and dodging blows.

|Wherewithal
|Whe
|aka "grit"; used to take damage, exert yourself, and resist body-affecting magic.

|Sociality
|Soc
|used to bargain for goods and convince or intimidate people.
|===

== The Law of Successes

*1 success = 1 fact or 1 die*

For every success on a roll: 
* you can decide to either state one fact about your action
* or carry that success over as a bonus die into another related roll

== Spending Tests for Wealth
=== Buying Items

*Player Roll = Wealth Dice + Sociality*

* Wealth Dice = choose up to max of current Wealth; if roll is *successful*, lose this many Wealth. If *unsuccessful*, keep these dice.

*Game Master Roll = Item Value + Markup*

* Item Value: See Item Value reference table
* Markup: Markup value assigned to Town or individual NPC

Success: Item is successfully acquired. Wealth Dice used in roll are removed.

Failure: Wealth Dice are _not_ removed. Merchant will not consider selling to character again until they have acquired more Wealth or circumstances have changed (e.g. have done a favor; increased Sociality)

=== Buying Provisions

Buying Provisions is identical to Buying an Item, except when the roll is successful, the player's Provisions dice increases by the number of successes the player had instead of simply acquiring an item.

=== Buying Influence (aka Bribing)

Used to influence or straight-up bribe an NPC. This roll is intended to provide Bonus Dice to a related social attempt, but is not the social attempt itself.

*Player Roll = Wealth Dice + Sociality*

* Wealth Dice = choose up to max of current Wealth; if roll is *successful*, lose this many Wealth. If *unsuccessful*, keep these dice.

*Game Master Roll = NPC's Current Wealth + Discernment*

* Note: NPC does not lose any Wealth in this interaction.

Success: If you succeed in this roll, you may add the number of successes you received to the number of dice you roll the next time your character attempts any sort of social proposition with the influenced NPC.

Failure: Not explicitly stated in Rules. But NPC is probably not happy.

== Spending Test for Provisions

Used to retrieve an item from your Provisions. This is a roll that you make when you want to retrieve an item from your backpack or other place of storage. You can only retrieve items that you have already acquired, and you must have enough Provisions to retrieve the item.


*Player Roll = Provisions + Cerebrality + Abilities*

* Provisions: The number of dice you are using from your Provisions pool.
* Abilities: Any relevant Abilities your character has.

*Game Master Roll = 3 + Max of Item's Worth OR Item's Ability score + 3(for rare items)*

* Item's Ability score: If the player wants the item to have an Ability, the score may be set between 1-4.
* +3(for rare items): If the item is not something you would usually carry, or is too large to fit in a backpack, add 3 to the roll.

Success: If you succeed in this roll, you retrieve the item from your Provisions pool and can use it as normal. Provisions dice used in roll are removed from your Provisions pool.

Failure: The item is not retrieved. Provisions dice used in roll are _not_ removed from your Provisions pool.

== Selling Items

=== Selling for Wealth
Used to sell an item directly in an attempt to increase your Wealth.

*Player Roll = Item's Worth + Sociality*

*Game Master Roll = Player's Current Wealth + Merchant's Markup*

Success: Any successes are added to your Wealth score, and the item is removed from your Provisions.

Failure: The item is removed regardless, and your Wealth score does _not_ increase.

=== Use an Item in Trade
Use an Item in trade as part of a larger transaction, such as buying an item or acquiring Provisions.

Make a Wealth Spending Test, and add the Item's Worth dice to the Player Roll. Item is _not_ lost upon failure. 


== Combat

=== Initiative

Players and NPCs each roll for Initiative using this formula:

*Initiative Roll = Player/NPC Level + Discernment*

* Write down all individual results or keep each die. 

Initiative order is resolved starting at 20, then 19, etc. Ties in Initiative are by highest Adroitness, then Player vs. NPC (Players first). If a Player or NPC has multiple dice for the same Initiative value, they should take one action, then let the rest of the round complete before taking another action.

=== Distance

Distances are:

* Out of range: Cannot attack or be attacked. Out of combat.
* Two actions away: -3 dice to missile weapons; cannot throw weapons or melee
* One action away: no penalty to missile or thrown; cannot melee
* Close: Can melee; -6 penalty to missile or thrown weapons
** If in Close and moving away, an opponent gets a free attack against you. 

It's abstract. Don't overthink it.

=== Movement & Resisting Movement

A Player or NPC can move one distance closer or away from an opponent as their action. 

* If the mover is currently in Close distance and moving away, their opponent gets a free attack.

*Uncontested Movement*: If the opponent is not resisting, the movement happens without interference.

*Resisting Movement*: If an opponent is resisting the movement, both sides roll:

*Roll = Adroitness + any relevant Abilities*

* The resister removes their next initiative die, representing the effort it takes to resist the movement.
* If the mover is successful, they move successfully.
* In either case, successess can be used per the Law of Successes.
* (!) If the Resister wins, they can instead choose to use their Resist Movement successes as bonus dice for their free attack roll.

=== Attacking

*Attacker and Defender Roll = Adroitness + any relevant Abilities*

* NOTE: Weapon Damage Rating is NOT used here.

Defender can choose to Parry or Dodge:

[cols="1,3"]
|===
h|Parry
a| * Defender actively defends with a _melee_ weapon or spell, intending to block and counterattack.
* Only Melee attacks can be Parried.
* Remove the next Initiative die from the Defender's pool, representing the effort it takes to Parry.
* Any successes for the Defender are then used in a Damage Test by the Defender.

h|Dodge
a| * Defender attempts to avoid the attack, but not return damage.
* No initiative die is removed.
* Success means no damage is taken.
|===

=== Damage & Injury

General Tip: Most damage happens as a second roll after a successful action or attack. Per Law of Successes, successes from the first roll can be used as bonus dice in the second roll.

* 1st roll - Player tries to climb cliff, falls down; 2nd roll - Damage Test
* 1st roll - Player attacks with sword, hits; 2nd roll - Damage Test
* 1st roll - Player rolls to disarm trap, fails; 2nd roll - Damage Test
* 1st roll - Player rolls to pick lock, fails; 2nd roll - Damage Test against the lockpick (damage applies to Ability Score of item, which breaks if it reaches 0)

*Attacker Damage Roll = Virility + Weapon Damage Rating + any relevant Abilities*

*Defender Damage Roll = Wherewithal + Armore Damage Rating + any relevant Abilities*

* Successes are applied to Flesh Wounds or Attributes
* For Player attacks, this is up to Player choice. For NPC attacks, damage applies to Flesh Wounds first, then Attributes.
* NPCs fall unconscious at 0 Flesh Wounds. PCs must be Smashed to fall unconscious.

*Smashed* = Damage Test against PC comes up ALL successes

=== Healing

* Automatically heal 1 Flesh Wound or Attribute die at beginning of each scene (Attributes first).
* All damage is healed between Adventures.
* Healing can also be done with items or Magic.

== Magic

=== Gathering Power

=== Casting a Spell

=== Creating Magic Items


== Loot

== Advancement




